import {test,expect} from '@playwright/test';
test('pair lab changes types, perspectives and scenes while retaining all sixteen profiles',async({page})=>{
 await page.goto('/?view=characters');const lab=page.getByRole('region',{name:'MBTI会話ラボ'});await expect(lab).toBeVisible();await expect(page.locator('.type-card')).toHaveCount(16);
 await page.getByLabel('話す側のタイプ').selectOption('INTJ');await page.getByLabel('受け取る側のタイプ').selectOption('ESFP');const first=await page.locator('.lab-bridge').innerText();await page.getByRole('button',{name:'意見が割れる',exact:true}).click();await expect(page.locator('.lab-bridge')).not.toHaveText(first);await page.getByRole('button',{name:'話す側と受け取る側を入れ替える'}).click();await expect(page.getByLabel('話す側のタイプ')).toHaveValue('ESFP');await expect(page.getByLabel('受け取る側のタイプ')).toHaveValue('INTJ');await page.getByRole('button',{name:'松尾 → 八阪',exact:true}).click();await expect(page.getByLabel('話す側のタイプ')).toHaveValue('INTJ');await expect(page.getByLabel('受け取る側のタイプ')).toHaveValue('ENFJ');await page.getByRole('button',{name:'困っている相手を助ける',exact:true}).click();await expect(page.locator('.lab-bridge')).toContainText('いちばん気になっている');await lab.getByText('4つの違いを見比べる').click();await expect(page.locator('.lab-axis>div')).toHaveCount(4);
 for(const width of [360,390,430,1440]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);}
});
test('actual mission message adapts to recipient with a plain alternative and survives reload unchanged',async({page})=>{
 await page.goto('/');await page.getByLabel('解決したい課題').fill('MBTI確認：接客品質を改善');await page.getByRole('button',{name:'編成と指示の初稿を作る'}).click();const raw=await page.evaluate(()=>localStorage.getItem('team-architect-v2'));const card=page.locator('.recipient-card').first();await card.getByRole('button',{name:/への伝達文を作る/}).click();const memo=page.getByLabel('そのまま伝える文章');await expect(memo).toHaveValue(/目指すこと：|今回の課題：/);await expect(memo).toHaveValue(/報告先：/);await page.getByRole('checkbox',{name:'MBTIを参考に、相手が受け取りやすい伝達文にする'}).uncheck();await card.getByRole('button',{name:/への伝達文を作る/}).click();await expect(memo).not.toHaveValue(/目指すこと：|今回の課題：/);expect(await page.evaluate(()=>localStorage.getItem('team-architect-v2'))).toBe(raw);await page.reload();await page.getByRole('button',{name:/MBTI確認：接客品質を改善/}).first().click();await expect(page.getByRole('heading',{name:'誰に、何を伝える？'})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('team-architect-v2'))).toBe(raw);
});
