import { test, expect } from '@playwright/test';
const issue='競合店のリニューアルに対抗して夜稼働を上げたい';
async function create(page:import('@playwright/test').Page){await page.goto('/');await page.getByLabel('解決したい課題').fill(issue);await page.getByLabel('達成したい状態').fill('夜の稼働低下を止める');await page.getByLabel('ミッション期限').fill('2026-10-13T18:00');await page.getByText('制約・KPI・参加メンバーを設定').click();await page.getByLabel('次回チェックポイント').fill('2026-10-07T12:00');await page.getByRole('button',{name:'編成と指示の初稿を作る'}).click();await expect(page.getByRole('heading',{name:issue,exact:true})).toBeVisible();await page.getByRole('tab',{name:'進捗・詳細'}).click();}
test('mission → independent hierarchy → actionable commands → task update → reload',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await create(page);await expect(page.getByText('最終判断者',{exact:true})).toBeVisible();await expect(page.getByText('KPIの現状値',{exact:true})).toBeVisible();await page.getByRole('button',{name:'確認して実行を開始'}).click();await expect(page.getByText('承認した指示を実行中')).toBeVisible();await page.getByRole('tab',{name:/個別指示/}).click();await expect(page.locator('.simple-commands')).toContainText('比較表と主要論点（1ページ）');await page.getByRole('button',{name:'指示・状態を編集'}).first().click();const dialog=page.getByRole('dialog');await dialog.getByLabel('状態',{exact:true}).selectOption('done');await dialog.getByLabel('成果物・確認結果・相談内容').fill('比較表を前﨑店長へ提出済み');await dialog.getByLabel('変更理由・引継ぎ事項').fill('分析成果物を確認して完了');await dialog.getByRole('button',{name:'変更を保存'}).click();await expect(dialog).toHaveCount(0);await page.reload();await page.getByRole('button',{name:/実行中.*競合店のリニューアル/}).click();await page.getByRole('tab',{name:/個別指示/}).click();await expect(page.locator('.simple-commands')).toContainText('比較表を前﨑店長へ提出済み');expect(errors).toEqual([]);for(const w of [360,390,430]){if(test.info().project.name==='mobile'){await page.setViewportSize({width:w,height:844});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);expect(overflow).toBe(false);}}});
test('legacy settings preserved and JSON backup can be imported in a clean browser',async({page,context})=>{await page.goto('/');await page.evaluate(()=>{localStorage.setItem('team-architect-capabilities','{"1-3":"growth"}');localStorage.setItem('team-architect-history','[{"id":1,"issue":"旧ミッション"}]');});await page.reload();await create(page);await page.getByRole('button',{name:'保存・履歴',exact:true}).click();await page.getByText('旧履歴の原文を表示').click();await expect(page.locator('pre')).toContainText('旧ミッション');const promise=page.waitForEvent('download');await page.getByRole('button',{name:'全データを書き出す'}).click();const download=await promise;const file=await download.path();expect(file).toBeTruthy();const next=await context.browser()!.newContext();const p=await next.newPage();await p.goto('/');await p.getByRole('button',{name:'保存・履歴',exact:true}).click();await p.locator('input[type=file]').setInputFiles(file!);await expect(p.getByText('バックアップを追加しました。既存データは保持しています。')).toBeVisible();await expect(p.getByRole('button',{name:new RegExp(issue)})).toBeVisible();await next.close();});
test('missing values stay unknown and activation blocked until configured',async({page})=>{await page.goto('/');await page.getByLabel('解決したい課題').fill('スタッフ育成を進めたい');await page.getByRole('button',{name:'編成と指示の初稿を作る'}).click();await page.getByRole('button',{name:'確認して実行を開始'}).click();await expect(page.getByRole('alert')).toContainText('期限');await page.getByRole('tab',{name:'進捗・詳細'}).click();await expect(page.getByText('KPIの目標値',{exact:true})).toBeVisible();});
test('corrupt storage protects original while UI remains usable',async({page})=>{await page.goto('/');await page.evaluate(()=>localStorage.setItem('team-architect-v2','broken'));await page.reload();await expect(page.getByRole('alert')).toContainText('元データの上書きを止め');await page.getByLabel('解決したい課題').fill('テスト');await page.getByRole('button',{name:'編成と指示の初稿を作る'}).click();expect(await page.evaluate(()=>localStorage.getItem('team-architect-v2'))).toBe('broken');});
test('interview application is intact and opens model answers',async({page})=>{await page.goto('/interview/');await expect(page.locator('body')).toContainText('面接');await expect(page.locator('body')).not.toContainText('MISSION FIRST');await page.getByRole('button',{name:/模範解答を見る/}).click();await expect(page.locator('#modelPanel')).toBeVisible();const before=await page.locator('#question').textContent();await page.getByRole('button',{name:'次の質問',exact:true}).click();await expect(page.locator('#question')).not.toHaveText(before!);});


test('all sixteen character portraits load and selection opens work-style guidance',async({page})=>{
 test.setTimeout(60000);
 await page.goto('/?view=characters');await expect(page.getByRole('heading',{name:'16の個性。ひとつのチーム。'})).toBeVisible();
 const cards=page.locator('.type-card');await expect(cards).toHaveCount(16);
 for(let i=0;i<16;i++){const card=cards.nth(i);const type=await card.locator('small').textContent();await card.click();await expect(card).toHaveAttribute('aria-pressed','true');await expect(page.locator('#character-detail')).toContainText(type!);for(const label of ['強み','弱み','得意','不得意'])await expect(page.locator('#character-detail dt').getByText(label,{exact:true})).toBeVisible();await expect(page.locator('#character-detail')).toContainText('伝え方の参考');await expect.poll(()=>page.locator('#character-detail img').evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);}
 for(const width of [360,390,430,1440]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);}
});

test('practical cockpit: KPI → hold → decision → handoff → reload and backup',async({page,context})=>{
 test.setTimeout(60000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await create(page);
 await page.getByText('目的・KPI・期限を補う／変更する',{exact:true}).click();
 await page.getByLabel('指標の定義・単位',{exact:true}).fill('夜稼働率（%）');await page.getByLabel('確定する目標値',{exact:true}).fill('40%');await page.getByLabel('条件の変更理由').fill('目標を確定');await page.getByRole('button',{name:'条件を保存',exact:true}).click();
 await page.getByRole('button',{name:'確認して実行を開始'}).click();
 await page.getByLabel('実測値',{exact:true}).fill('38');await page.getByLabel('達成方向').selectOption('increase');await page.getByLabel('観測日時（日本時間）',{exact:true}).fill('2026-10-08T22:00');await page.getByLabel('観測対象の期間').fill('10月8日18〜22時');await page.getByLabel('実測値の出所').fill('日次稼働集計');await page.getByRole('button',{name:'実績を保存'}).click();await expect(page.locator('.actual-kpi')).toContainText('38');await expect(page.locator('.actual-kpi')).toContainText('目標未達');await page.getByText('次回確認日時を更新',{exact:true}).click();await page.getByLabel('次回確認日時',{exact:true}).fill('2026-10-11T18:00');await page.getByRole('button',{name:'確認日時を保存'}).click();await expect(page.locator('.checkpoint')).toContainText('2026-10-11 18:00');
 const related=page.getByLabel('関連する指示');const firstId=await related.locator('option').nth(1).getAttribute('value');await related.selectOption(firstId!);await page.getByLabel('判断してほしいこと').fill('比較データが不足');await page.getByLabel('事実・影響・希望する対応').fill('競合の記録が未取得。明日までの延長と担当変更を相談。');await page.getByLabel('この指示を保留にする').check();await page.getByRole('button',{name:'相談を保存'}).click();await expect(page.locator('.decision-item')).toContainText('比較データが不足');await expect(page.locator('.execution-task').first()).toContainText('要相談');await expect(page.locator('.next-action h2')).not.toHaveText('現状分析');
 await page.getByLabel('判断結果・次の行動').fill('翌日まで延長。宮本へ途中資料を引き継ぐ。');await page.getByRole('button',{name:'判断結果を保存'}).click();await expect(page.locator('.decision-item')).toHaveCount(0);await expect(page.locator('.execution-task').first()).toContainText('要相談');
 await page.locator('.execution-task').first().getByRole('button',{name:'進捗・指示を更新'}).click();const dialog=page.getByRole('dialog');const owner=dialog.getByLabel('実行担当',{exact:true});const current=await owner.inputValue();const alternative=await owner.locator('option').evaluateAll((options,current)=>options.map(o=>({value:(o as HTMLOptionElement).value,text:o.textContent})).find(o=>o.value!==current),current);await owner.selectOption(alternative!.value);await dialog.getByLabel('状態',{exact:true}).selectOption('doing');await dialog.getByLabel('変更理由・引継ぎ事項').fill('担当不在のため途中資料を引継ぎ、データ取得を再開');await dialog.getByLabel('期限（日本時間）',{exact:true}).fill('2026-10-10T18:00');await dialog.getByRole('button',{name:'変更を保存'}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('.execution-task').first()).toContainText(alternative!.text!);await expect(page.locator('.execution-task').first()).toContainText('進行中');await expect(page.locator('.change-entry').last()).toBeVisible();
 await page.reload();await page.getByRole('button',{name:'実行司令室を開く'}).click();await page.getByRole('tab',{name:'進捗・詳細'}).click();await expect(page.locator('.actual-kpi')).toContainText('38');await expect(page.locator('.execution-task').first()).toContainText(alternative!.text!);await expect(page.getByText('解決済みの判断（1件）',{exact:true})).toBeVisible();
 for(const width of [360,390,430,1440]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);}
 await page.getByRole('button',{name:'保存・履歴',exact:true}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'全データを書き出す'}).click();const download=await downloadPromise;const file=await download.path();const clean=await context.browser()!.newContext();const restored=await clean.newPage();await restored.goto('/');await restored.getByRole('button',{name:'保存・履歴',exact:true}).click();await restored.locator('input[type=file]').setInputFiles(file!);await restored.getByRole('button',{name:/実行中.*競合店のリニューアル/}).click();await restored.getByRole('tab',{name:'進捗・詳細'}).click();await expect(restored.locator('.actual-kpi')).toContainText('38');await expect(restored.locator('.execution-task').first()).toContainText(alternative!.text!);await clean.close();expect(errors).toEqual([]);
});

test('draft missing conditions can be completed in place without recreating mission',async({page})=>{
 await page.goto('/');await page.getByLabel('解決したい課題').fill('スタッフ育成');await page.getByRole('button',{name:'編成と指示の初稿を作る'}).click();await page.getByRole('tab',{name:'進捗・詳細'}).click();await page.getByText('目的・KPI・期限を補う／変更する',{exact:true}).click();await page.getByLabel('確定する目的').fill('新人が接客手順を説明できる');await page.getByLabel('確定する期限').fill('2026-10-15T18:00');await page.getByLabel('確定する確認日時').fill('2026-10-10T12:00');await page.getByLabel('未完了の指示にも目的・期限・報告日時を反映する').check();await page.getByLabel('条件の変更理由').fill('現場確認後に目的と日程を確定');await page.getByRole('button',{name:'条件を保存',exact:true}).click();await page.getByRole('button',{name:'確認して実行を開始'}).click();await expect(page.getByText('承認した指示を実行中')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('team-architect-v2')!).missions.length)).toBe(1);
});
