import { useState, type FormEvent } from 'react';
import { Activity, AlertTriangle, ArrowRight, Clock, History, Target } from 'lucide-react';
import { actionable, executionOf, isOverdue, kpiComparison, raiseDecision, recordObservation, resolveDecision, timestamp, waitingOn, type Execution } from '../core/execution';
import { nameOf, specs, type Command, type Mission } from '../core/mission';
import { MissionConditions } from './MissionConditions';

type Props={mission:Mission;onSave:(m:Mission)=>boolean;onEdit:(c:Command)=>void};
const time=(s:string)=>s?s.replace('T',' ')+' JST':'未設定';
const recordedTime=(s:string)=>new Date(s).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'});
const statuses={todo:'未着手',doing:'進行中',blocked:'要相談',done:'完了'};
export function ExecutionBoard({mission:m,onSave,onEdit}:Props){
 const e=executionOf(m);const [person,setPerson]=useState('all');const [error,setError]=useState('');
 const [observation,setObservation]=useState({value:'',observedAt:'',source:m.brief.source,period:m.brief.period,recordedBy:(m.team.find(t=>t.role==='LEADER')||m.team.find(t=>t.role!=='COMMANDER')||m.team[0]).memberId});
 const [direction,setDirection]=useState<Execution['direction']>(e.direction);
 const [report,setReport]=useState({title:'',detail:'',commandId:'',raisedBy:(m.team.find(t=>t.role==='LEADER')||m.team.find(t=>t.role!=='COMMANDER')||m.team[0]).memberId,urgency:'normal' as 'normal'|'immediate',due:'',hold:false});
 const [resolution,setResolution]=useState<Record<string,string>>({});
 const [checkpoint,setCheckpoint]=useState<string|null>(null);
 const ready=actionable(m);const next=ready[0];const compare=kpiComparison(m);const open=e.decisions.filter(d=>d.status==='open').sort((a,b)=>Number(b.urgency==='immediate')-Number(a.urgency==='immediate'));
 const blocked=m.commands.filter(c=>c.status==='blocked');const overdue=m.commands.filter(c=>isOverdue(c));const done=m.commands.filter(c=>c.status==='done').length;
 function attempt(fn:()=>Mission,after?:()=>void){try{if(onSave(fn())){setError('');after?.();}}catch(err){setError(err instanceof Error?err.message:String(err));}}
 function saveObservation(event:FormEvent){event.preventDefault();attempt(()=>recordObservation(m,{...observation,value:Number(observation.value)},direction),()=>setObservation({...observation,value:'',observedAt:''}));}
 function saveReport(event:FormEvent){event.preventDefault();attempt(()=>raiseDecision(m,{...report,commandId:report.commandId||null},report.hold),()=>setReport({...report,title:'',detail:'',hold:false}));}
 function saveCheckpoint(event:FormEvent){event.preventDefault();const value=checkpoint??m.brief.checkpoint;if(!Number.isFinite(timestamp(value))){setError('確認日時を設定してください。');return;}const actor=m.team.find(t=>t.role==='COMMANDER')!.memberId;attempt(()=>({...m,brief:{...m.brief,checkpoint:value},execution:{...e,changes:[...e.changes,{id:crypto.randomUUID(),commandId:null,actor,reason:'次回確認日時の更新',before:time(m.brief.checkpoint),after:time(value),at:new Date().toISOString()}]}}),()=>setCheckpoint(null));}
 return <div className="execution-board">
 {error&&<p className="execution-error" role="alert">{error}</p>}
 <div className="execution-summary" aria-label="実行状況"><div><b>{done}/{m.commands.length}</b><span>完了</span></div><a href="#decision-queue"><b>{open.length}</b><span>判断待ち ↓</span></a><div><b>{blocked.length}</b><span>保留</span></div><div><b>{overdue.length}</b><span>期限超過</span></div></div>
 <div className="dashboard-grid"><section className="panel current-goal"><small>CURRENT OBJECTIVE</small><h2>{m.brief.goal||'達成したい状態を確認する'}</h2><progress aria-label="タスク完了" value={done} max={m.commands.length}/><div className="kpi-row"><div><small>KPI</small><b>{m.brief.kpi||'未設定'}</b></div><div><small>基準 → 目標</small><b>{m.brief.baseline||'未確認'} → {m.brief.target||'未設定'}</b></div></div><div className="actual-kpi"><small>最新の実測値</small><strong>{compare.latest?compare.latest.value:'未記録'}</strong><span>{compare.achieved===null?'達成判定：未確認':compare.achieved?'目標達成':'目標未達'}{compare.gap!==null&&` / 目標との差 ${compare.gap>0?'+':''}${Math.round(compare.gap*1000)/1000}`}</span></div>{compare.latest&&<p className="subtle">観測：{time(compare.latest.observedAt)}<br/>期間：{compare.latest.period} ／ 出所：{compare.latest.source}</p>}<small>タスク完了数とKPIの成果は別に確認します。</small></section>
 <section className="panel next-action"><small>NEXT ACTION / 次の30分の初動</small><h2>{open.some(d=>d.urgency==='immediate')?'即時報告を優先':next?specs[next.fn].name:done===m.commands.length?'結果を確認する':'判断待ち・先行成果物を確認'}</h2><p>{open.some(d=>d.urgency==='immediate')?'安全を確保し、前﨑店長へ直接連絡してください。記録だけでは連絡されません。':next?next.actions[0]:done===m.commands.length?'KPIの実績と成果物を最終判断者へ提出してください。':'保留理由と先行成果物を確認し、担当・期限・再開条件を決めてください。'}</p>{next&&<><div className="owner-chip">{nameOf(next.owner)} → 報告：{nameOf(next.reportTo)}</div><button className="text-button" onClick={()=>onEdit(next)}>初動の指示を確認・更新<ArrowRight size={16}/></button></>}<hr/><small>NEXT CHECKPOINT / 日本時間</small><b className="checkpoint">{time(m.brief.checkpoint)}</b>{m.brief.checkpoint&&timestamp(m.brief.checkpoint)<Date.now()&&<p className="deadline-warning">確認時刻を過ぎています。状況を確認して次回日時を更新してください。</p>}<details><summary>次回確認日時を更新</summary><form onSubmit={saveCheckpoint}><label className="field">次回確認日時<input required type="datetime-local" value={checkpoint??m.brief.checkpoint} onChange={ev=>setCheckpoint(ev.target.value)}/></label><button className="secondary" type="submit">確認日時を保存</button></form></details></section></div>
 <MissionConditions key={m.id+':'+m.brief.goal+':'+m.brief.deadline+':'+m.brief.checkpoint} mission={m} onSave={onSave}/>
 <section className="panel task-board"><div className="section-label"><Clock size={18}/>今日動かす仕事<span>担当・報告先・期限</span></div><label className="field task-filter">担当で絞り込む<select value={person} onChange={ev=>setPerson(ev.target.value)}><option value="all">全員</option>{m.team.filter(t=>t.role!=='COMMANDER').map(t=><option key={t.memberId} value={t.memberId}>{nameOf(t.memberId)}</option>)}</select></label><div className="execution-tasks">{m.commands.filter(c=>person==='all'||c.owner===person).map(c=><article className={'execution-task '+(c.status==='done'?'completed':'')} key={c.id}><div><span className={'task-state '+c.status}>{statuses[c.status]}</span>{isOverdue(c)&&<span className="deadline-warning">期限超過</span>}<h3>{specs[c.fn].name} / {nameOf(c.owner)}</h3><p>{c.actions[0]}</p><small>報告：{nameOf(c.reportTo)} ／ 期限：{time(c.due)}</small>{waitingOn(m,c).length>0&&<p className="task-wait">先行待ち：{waitingOn(m,c).map(id=>specs[m.commands.find(p=>p.id===id)!.fn].name).join('・')}</p>}{c.status==='blocked'&&<p className="deadline-warning">相談内容：{c.evidence||'下の「相談・要判断を記録」で理由を残してください。'}</p>}</div><button className="secondary" onClick={()=>onEdit(c)}>{c.status==='done'?'成果物を確認':'進捗・指示を更新'}</button></article>)}</div></section>
 <div className="two-column"><section className="panel"><div className="section-label"><Target size={18}/>KPI実績を記録</div><p className="subtle">{m.brief.kpi||'指標の定義・単位は未設定です。入力時と同じ単位の実測値を記録してください。'}。目標が数値または数値＋%の場合に比較します。</p><form onSubmit={saveObservation}><div className="field-grid"><label className="field">実測値<input required type="number" step="any" value={observation.value} onChange={ev=>setObservation({...observation,value:ev.target.value})}/></label><label className="field">達成方向<select required value={direction||''} onChange={ev=>setDirection(ev.target.value as Execution['direction'])}><option value="">選択してください</option><option value="increase">目標以上で達成</option><option value="decrease">目標以下で達成</option></select></label><label className="field">観測日時（日本時間）<input required type="datetime-local" value={observation.observedAt} onChange={ev=>setObservation({...observation,observedAt:ev.target.value})}/></label><label className="field">観測対象の期間<input required value={observation.period} onChange={ev=>setObservation({...observation,period:ev.target.value})} placeholder="例：10/8の18〜22時"/></label></div><label className="field">実測値の出所<input required value={observation.source} onChange={ev=>setObservation({...observation,source:ev.target.value})} placeholder="例：日次稼働集計"/></label><label className="field">記録者<select value={observation.recordedBy} onChange={ev=>setObservation({...observation,recordedBy:ev.target.value})}>{m.team.map(t=><option key={t.memberId} value={t.memberId}>{nameOf(t.memberId)}</option>)}</select></label><button className="primary" type="submit">実績を保存<Activity size={16}/></button></form><details className="execution-history"><summary>実績の履歴（{e.observations.length}件）</summary>{[...e.observations].reverse().map(o=><article key={o.id}><b>{o.value} / {time(o.observedAt)}</b><p>{o.period} ／ {o.source}</p><small>記録：{nameOf(o.recordedBy)} · {recordedTime(o.recordedAt)}</small></article>)}</details></section>
 <section className="panel"><div className="section-label"><AlertTriangle size={18}/>相談・要判断を記録</div><p className="subtle">直接の報告先へ集約します。即時報告は前﨑店長へ。アプリから通知は送られないため、必要な連絡は直接行ってください。</p><form onSubmit={saveReport}><label className="field">判断してほしいこと<input required value={report.title} onChange={ev=>setReport({...report,title:ev.target.value})} placeholder="例：データ不足のため期限を延ばしたい"/></label><label className="field">事実・影響・希望する対応<textarea required value={report.detail} onChange={ev=>setReport({...report,detail:ev.target.value})} rows={3}/></label><div className="field-grid"><label className="field">関連する指示<select value={report.commandId} onChange={ev=>setReport({...report,commandId:ev.target.value,hold:false})}><option value="">ミッション全体</option>{m.commands.map(c=><option key={c.id} value={c.id}>{specs[c.fn].name} / {nameOf(c.owner)}</option>)}</select></label><label className="field">報告の緊急度<select value={report.urgency} onChange={ev=>setReport({...report,urgency:ev.target.value as 'normal'|'immediate'})}><option value="normal">通常の相談</option><option value="immediate">即時報告（店長へ）</option></select></label><label className="field">報告者<select value={report.raisedBy} onChange={ev=>setReport({...report,raisedBy:ev.target.value})}>{m.team.map(t=><option key={t.memberId} value={t.memberId}>{nameOf(t.memberId)}</option>)}</select></label><label className="field">判断が必要な日時（日本時間）<input type="datetime-local" value={report.due} onChange={ev=>setReport({...report,due:ev.target.value})}/></label></div>{report.commandId&&m.commands.find(c=>c.id===report.commandId)?.status!=='done'&&<label className="hold-check"><input type="checkbox" checked={report.hold} onChange={ev=>setReport({...report,hold:ev.target.checked})}/>この指示を保留にする</label>}<button className="primary" type="submit">相談を保存</button></form></section></div>
 <section className="panel decision-queue" id="decision-queue"><div className="section-label"><AlertTriangle size={18}/>今、決めること<span>{open.length}件の判断待ち</span></div>{!open.length&&<p className="subtle">判断待ちはありません。問題が出たら、事実と希望する対応を記録してください。</p>}{open.map(d=><article className={'decision-item '+d.urgency} key={d.id}><span className="decision-badge">{d.urgency==='immediate'?'即時報告':'判断待ち'}</span><h3>{d.title}</h3><p>{d.detail}</p><small>報告：{nameOf(d.raisedBy)} → 判断：{nameOf(d.owner)} ／ 期限：{time(d.due)}</small>{d.due&&timestamp(d.due)<Date.now()&&<p className="deadline-warning">判断期限を過ぎています。</p>}<form onSubmit={ev=>{ev.preventDefault();attempt(()=>resolveDecision(m,d.id,resolution[d.id]||'',d.owner));}}><label className="field">判断結果・次の行動<textarea required value={resolution[d.id]||''} onChange={ev=>setResolution({...resolution,[d.id]:ev.target.value})} placeholder="決定内容、担当、期限、再開条件を記録"/></label><p className="subtle">{nameOf(d.owner)}の判断を記録します。保留中の仕事は、指示を更新して再開してください。</p><button className="secondary" type="submit">判断結果を保存</button>{d.commandId&&<button className="text-button" type="button" onClick={()=>onEdit(m.commands.find(c=>c.id===d.commandId)!)}>関連指示を修正<ArrowRight size={16}/></button>}</form></article>)}<details className="execution-history"><summary>解決済みの判断（{e.decisions.filter(d=>d.status==='resolved').length}件）</summary>{e.decisions.filter(d=>d.status==='resolved').map(d=><article key={d.id}><b>{d.title}</b><p>{d.resolution}</p><small>判断：{nameOf(d.resolvedBy)} ／ {recordedTime(d.resolvedAt)}</small></article>)}</details></section>
 <section className="panel"><div className="section-label"><History size={18}/>再指示・引継ぎの履歴<span>{e.changes.length}件</span></div><p className="subtle">端末内の記録です。担当変更で決裁権限は変更しません。判断者名は記録上の表示で、本人認証ではありません。</p>{[...e.changes].reverse().map(c=><details className="change-entry" key={c.id}><summary>{c.reason} / {nameOf(c.actor)}<small>{recordedTime(c.at)}</small></summary><div className="change-comparison"><div><b>変更前</b><pre>{c.before}</pre></div><div><b>変更後</b><pre>{c.after}</pre></div></div></details>)}{!e.changes.length&&<p className="subtle">指示・担当・確認日時の変更をここに残します。</p>}</section>
 </div>;
}
