import { useState } from 'react';
import { people, typeBook } from '../core/data';
import { pairReading, scenes, typeQuestions, type Scene } from '../core/mbti';
import { TypePortrait } from './TypePortrait';
export function MbtiLab(){
 const [from,setFrom]=useState('ENTJ'),[to,setTo]=useState('INFP'),[scene,setScene]=useState<Scene>('request');
 const reading=pairReading(from,to,scene);
 function person(type:string,side:'from'|'to'){const t=typeBook.find(t=>t.mbti===type)!;return <div className="lab-person"><TypePortrait type={type} eager/><div><label className="field">{side==='from'?'話す側':'受け取る側'}<select aria-label={side==='from'?'話す側のタイプ':'受け取る側のタイプ'} value={type} onChange={e=>side==='from'?setFrom(e.target.value):setTo(e.target.value)}>{typeBook.map(t=><option key={t.mbti} value={t.mbti}>{t.mbti} / {t.jp}</option>)}</select></label><h3>{t.jp}</h3><p>「{typeQuestions[type]}」</p></div></div>;}
 return <section className="panel mbti-lab" aria-label="MBTI会話ラボ"><div className="section-title"><div><small>PAIR LAB / MBTIを使ってみる</small><h2>この2人、どう組む？</h2><p>同じ話でも、相手を変えると入口が変わる。</p></div><button className="secondary" onClick={()=>{setFrom(to);setTo(from);}}>話す側と受け取る側を入れ替える</button></div><div className="lab-presets"><span>チームで試す</span>{[['maesaki','hattori'],['matsuo','yasaka'],['miyamoto','asano']].map(([a,b])=>{const x=people.find(p=>p.id===a)!,y=people.find(p=>p.id===b)!;return <button className="secondary" key={a} onClick={()=>{setFrom(x.mbti);setTo(y.mbti);}}>{x.name} → {y.name}</button>;})}</div><div className="lab-pair">{person(from,'from')}{person(to,'to')}</div><div className="lab-scenes" role="group" aria-label="会話の場面">{Object.entries(scenes).map(([id,label])=><button className={scene===id?'primary':'secondary'} aria-pressed={scene===id} key={id} onClick={()=>setScene(id as Scene)}>{label}</button>)}</div><div className="lab-dialogue" aria-live="polite"><p><b>{from}の入口</b>「{reading.opening}」</p><p><b>{to}が確かめたいこと</b>「{reading.response}」</p><div className="lab-bridge"><small>GAME MASTER / つなぐ一言</small><h3>「{reading.bridge}」</h3></div></div><div className="lab-insights"><div><h3>補い合えるところ</h3><p>{reading.complement}</p></div><div><h3>すれ違いやすいところ</h3><p>{reading.friction}</p></div></div><details><summary>4つの違いを見比べる</summary><div className="lab-axis">{reading.axisRows.map(a=><div key={a.name}><b>{a.name}</b><span>{from}：{a.from}</span><span>{to}：{a.to}</span><small>{a.different?a.bridge:'共通の入口。違う考え方も一度聞いてみる。'}</small></div>)}</div></details><p className="portrait-note">傾向を使った創作の会話例です。相性の点数や能力評価ではありません。本人の希望・実際の反応で調整してください。ミッションの「伝達文」でも相手のタイプに合わせた入口を使えます。</p></section>;
}
