import { useState } from 'react';
import { people } from '../core/data';
import { nameOf, specs, type Command, type Mission } from '../core/mission';
import { OperativePortrait } from './OperativePortrait';
const statusNames={todo:'未着手',doing:'進行中',blocked:'要相談',done:'完了'};
export function SimpleCommands({mission,onEdit}:{mission:Mission;onEdit:(c:Command)=>void}){
 const [owner,setOwner]=useState('all');const [memo,setMemo]=useState('');
 const recipients=people.filter(p=>mission.commands.some(c=>c.owner===p.id));
 function message(commands:Command[]){return commands.map(c=>`${nameOf(c.owner)}さんへ｜${specs[c.fn].name}（${statusNames[c.status]}）\n${c.actions[0]}\n仕上げるもの：${c.output}\n期限：${c.due?c.due.replace('T',' ')+' JST':'未設定'} / 報告先：${nameOf(c.reportTo)}${c.status!=='done'&&c.dependsOn.some(id=>mission.commands.find(x=>x.id===id)?.status!=='done')?'\n先行作業の完了後に着手してください。':''}`).join('\n\n');}
 return <section className="simple-commands" aria-label="誰に何を伝えるか"><div className="simple-toolbar"><h2>誰に、何を伝える？</h2><label>伝える相手<select aria-label="伝える相手" value={owner} onChange={e=>{setOwner(e.target.value);setMemo('');}}><option value="all">全員</option>{recipients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="recipient-grid">{recipients.filter(p=>owner==='all'||p.id===owner).map(p=>{const commands=mission.commands.filter(c=>c.owner===p.id);return <article className="panel recipient-card" key={p.id}><header><OperativePortrait memberId={p.id}/><div><h3>{p.name}さんへ</h3><small>{p.mbti} · {commands.length}件</small></div></header>{commands.map(c=>{const waiting=c.dependsOn.some(id=>mission.commands.find(x=>x.id===id)?.status!=='done');return <div className="short-command" key={c.id}><div className="short-label"><b>{specs[c.fn].name}</b><small>{statusNames[c.status]}{waiting&&c.status!=='done'?' · 先行待ち':''}</small></div><p>{c.actions[0]}</p><small>仕上げるもの：{c.output}</small><small>期限：{c.due?c.due.replace('T',' ')+' JST':'未設定'} · 報告：{nameOf(c.reportTo)}</small><details><summary>指示の続きを見る</summary><ol>{c.actions.slice(1).map((x,i)=><li key={i}>{x}</li>)}</ol><p>完了条件：{c.done}</p><p>報告：{c.reportWhen}</p><p>相談：{c.consult}</p><p>即時報告：{c.immediate}</p><p>任せる範囲：{c.discretion}</p><p>伝え方の参考：{c.style}</p></details>{c.evidence&&<p className="subtle">記録：{c.evidence}</p>}<button className="secondary" onClick={()=>onEdit(c)}>指示・状態を編集</button></div>})}<button className="primary" onClick={()=>setMemo(message(commands))}>{p.name}への伝達文を作る</button></article>})}</div>{memo&&<section className="panel delivery-memo"><label className="field">そのまま伝える文章<textarea aria-label="そのまま伝える文章" readOnly rows={8} value={memo} onFocus={e=>e.target.select()}/></label><small>選択してコピーできます。</small></section>}</section>;
}
