import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowRight, Check, ChevronDown, Clipboard, Compass, Download, Flag, LayoutDashboard, Network, Plus, Radio, ShieldAlert, Target, Upload, Users } from 'lucide-react';
import { abilityNames, people, typeBook, functionStack, type Level } from './core/data';
import { activationIssues, assessment, blankBrief, commandText, createMission, kindLabels, nameOf, specs, type Brief, type Command, type Mission, type Status, validateMission } from './core/mission';
import { loadStore, mergeStore, parseStore, saveStore, STORE_KEY, type Store } from './core/storage';

import { OperativePortrait, RoleEmblem } from './components/OperativePortrait';

type View='home'|'control'|'members'|'records';
const stateNames:Record<Status,string>={todo:'未着手',doing:'進行中',blocked:'要相談',done:'完了'};
const fmt=(x:string)=>x?x.replace('T',' ')+' JST':'未設定';
function download(filename:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function initial(){try{return {store:loadStore(localStorage),error:''};}catch(e){return {store:{schemaVersion:2,missions:[],overrides:{},legacy:{history:null,capabilities:null}} as Store,error:'保存データを読み込めません。元データの上書きを止めています。 '+String(e)};}}
export default function App(){
 const [loaded]=useState(initial);const [store,setStore]=useState(loaded.store);const [error,setError]=useState(loaded.error);const [notice,setNotice]=useState('');const [view,setView]=useState<View>('home');const [brief,setBrief]=useState<Brief>({...blankBrief});const [selected,setSelected]=useState(store.missions[0]?.id||'');const [tab,setTab]=useState<'overview'|'commands'>('overview');const [editor,setEditor]=useState<Command|null>(null);const [member,setMember]=useState('matsuo');const [book,setBook]=useState('INTJ');const [notes,setNotes]=useState('');
 const dialogRef=useRef<HTMLElement>(null);
 useEffect(()=>{
  if(!editor)return;
  const previous=document.activeElement as HTMLElement|null;
  const dialog=dialogRef.current;
  const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button,input,textarea,select,[tabindex="0"]')||[]);
  focusable()[0]?.focus();
  const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';
  const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setEditor(null);return;}if(e.key==='Tab'){const els=focusable();const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
  document.addEventListener('keydown',key);
  return ()=>{document.removeEventListener('keydown',key);document.body.style.overflow=oldOverflow;previous?.focus();};
 },[editor?.id]);
 const mission=store.missions.find(m=>m.id===selected);const active=store.missions.filter(m=>m.state==='active');const done=mission?.commands.filter(c=>c.status==='done').length||0;
 function persist(next:Store):boolean {try{if(loaded.error)throw new Error('元データ保護中です。原データを書き出してください。');saveStore(localStorage,next);setStore(next);setError('');setNotice('この端末に保存しました');return true;}catch(e){setError('保存できませんでした。画面の入力は保持しています。JSON書出しをご利用ください。 '+String(e));return false;}}
 function select(m:Mission){setSelected(m.id);setView('control');setTab('overview');setNotes(m.notes);setEditor(null);setNotice('');}
 function updateMission(m:Mission){const errors=validateMission(m);if(errors.length){setError(errors.join('／'));return false;}return persist({...store,missions:store.missions.map(old=>old.id===m.id?{...m,updatedAt:new Date().toISOString(),version:old.version+1}:old)});}
 function start(e:FormEvent){e.preventDefault();try{const m=createMission(brief,store.overrides);if(persist({...store,missions:[m,...store.missions]})){select(m);setBrief({...blankBrief});}}catch(e){setError(String(e));}}
 function activate(){if(!mission)return;const errors=activationIssues(mission);if(errors.length){setError(errors.join('／'));return;}updateMission({...mission,state:'active'});}
 function saveCommand(e:FormEvent){e.preventDefault();if(!editor||!mission)return;const c={...editor,actions:editor.actions.filter(x=>x.trim()),version:editor.version+1};if(c.status==='done'&&c.dependsOn.some(id=>mission.commands.find(x=>x.id===id)?.status!=='done')){setError('先行する成果物が未完了です。先行指示の確認後に完了へ変更してください。');return;}if(c.status==='done'&&!c.evidence.trim()){setError('完了には成果物・確認結果を記録してください。');return;}if(updateMission({...mission,commands:mission.commands.map(x=>x.id===c.id?c:x)}))setEditor(null);}
 function copy(c:Command){navigator.clipboard.writeText(commandText(c)).then(()=>setNotice('指示をコピーしました')).catch(()=>setError('コピーできません。指示を選択してコピーしてください。'));}
 function exportAll(){download('team-architect-backup.json',JSON.stringify({...store,workingInput:{brief,editor,notes}},null,2));setNotice('バックアップを書き出しました');}
 function rawExport(){try{download('team-architect-original.json',JSON.stringify({v2:localStorage.getItem(STORE_KEY),history:localStorage.getItem('team-architect-history'),capabilities:localStorage.getItem('team-architect-capabilities')},null,2));}catch(e){setError(String(e));}}
 async function importFile(file:File|undefined){if(!file)return;try{if(file.size>5*1024*1024)throw new Error('読込みは5MB以内です。');const incoming=parseStore(await file.text());const next=mergeStore(store,incoming);if(persist(next))setNotice('バックアップを追加しました。既存データは保持しています。');}catch(e){setError('読込みを中止しました。 '+String(e));}}
 const nav=[{id:'home' as const,label:'司令室',icon:LayoutDashboard},{id:'control' as const,label:'ミッション',icon:Flag},{id:'members' as const,label:'人材・MBTI',icon:Users},{id:'records' as const,label:'保存・履歴',icon:Clipboard}];
 const currentMember=people.find(p=>p.id===member)!;
 const nextTask=mission?.commands.find(c=>c.status!=='done'&&c.dependsOn.every(id=>mission.commands.find(p=>p.id===id)?.status==='done'));
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView('home');}}><span className="brand-icon"><Compass size={25}/></span><span>TEAM<br/><b>ARCHITECT <i>2.0</i></b></span></a><div className="workspace"><span className="live-dot"/>羽曳野店 <span>組織設計</span></div><nav aria-label="メインナビゲーション">{nav.map(item=><button key={item.id} className={view===item.id?'selected':''} onClick={()=>{setView(item.id);setEditor(null);}}><item.icon size={19}/>{item.label}{item.id==='control'&&store.missions.length>0&&<span className="count">{store.missions.length}</span>}</button>)}</nav><div className="sidebar-bottom"><Radio size={17}/><b>GAME MASTER</b><p>ルールによる提案<br/>生成AI：未接続</p><small>保存先：この端末<br/>端末間共有：なし</small></div></aside>
 <div className="main-shell"><header className="topbar"><div><span>COMMAND CENTER</span><b>{view==='home'?'司令室':view==='control'?'ミッションコントロール':view==='members'?'人材と仕事の接続':'保存と履歴'}</b></div><span className="mode"><span className="live-dot"/>RULE ENGINE / B1</span></header>
 <main>{error&&<div className="alert error" role="alert"><ShieldAlert size={19}/><div>{error}<button onClick={rawExport}>原データを書き出す</button><button onClick={()=>setError('')}>表示を閉じる</button></div></div>}{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
 {view==='home'&&<><section className="command-hero"><div className="hero-copy"><small><span className="live-dot"/> TEAM ARCHITECT / COMMAND ROOM</small><div className="hero-wordmark">BUILD THE TEAM.<br/><span>MOVE THE MISSION.</span></div><h1>今回のミッションは？</h1><p>人の強みをつなぎ、組織を動かす。<br/>あなたの判断を、チームの次の一手へ。</p><div className="hero-coordinate"><span>HABIKINO / UNIT 07</span><span>ORGANIZATION DESIGN 2.0</span></div></div><div className="hero-squad" aria-hidden="true"><OperativePortrait memberId="matsuo" className="hero-strategist"/><OperativePortrait memberId="maesaki" className="hero-commander"/><OperativePortrait memberId="miyamoto" className="hero-field"/><span className="hero-insignia">TA / 02</span><span className="hero-caption">COMMAND · STRATEGY · EXECUTION</span></div></section>
 <div className="home-grid"><section className="mission-input panel"><div className="section-label"><Target size={18}/>新しいミッション<span>01 / BRIEF</span></div><form onSubmit={start}><label className="field">解決したい課題<textarea required value={brief.issue} onChange={e=>setBrief({...brief,issue:e.target.value})} placeholder="例：競合店のリニューアルに対抗して夜稼働を上げたい" rows={4}/></label><div className="preset-row">{['競合店のリニューアルに対抗して夜稼働を上げたい','スタッフ育成を進めたい','接客品質を改善したい'].map((x,i)=><button type="button" key={x} onClick={()=>setBrief({...brief,issue:x})}>{['夜稼働の改善','スタッフ育成','接客品質の改善'][i]}</button>)}</div>
 <div className="field-grid"><label className="field">達成したい状態<input value={brief.goal} onChange={e=>setBrief({...brief,goal:e.target.value})} placeholder="例：夜時間帯の稼働低下を止める"/></label><label className="field">ミッション期限（日本時間）<input type="datetime-local" value={brief.deadline} onChange={e=>setBrief({...brief,deadline:e.target.value})}/></label></div>
 <details className="brief-details"><summary>制約・KPI・参加メンバーを設定<ChevronDown size={16}/></summary><label className="field">制約・守る条件<textarea value={brief.constraints} onChange={e=>setBrief({...brief,constraints:e.target.value})} placeholder="例：追加予算なし、通常営業の接客品質を維持" rows={2}/></label><div className="field-grid">{([['kpi','KPIの定義・単位','例：18〜22時の平均稼働率（%）'],['baseline','現状値','実測値を入力'],['target','目標値','目標を入力'],['source','データ取得元','例：日次稼働集計'],['period','観測期間','例：10月7日〜13日']] as const).map(([k,label,placeholder])=><label className="field" key={k}>{label}<input value={brief[k]} placeholder={placeholder} onChange={e=>setBrief({...brief,[k]:e.target.value})}/></label>)}<label className="field">次回チェックポイント（日本時間）<input type="datetime-local" value={brief.checkpoint} onChange={e=>setBrief({...brief,checkpoint:e.target.value})}/></label></div><fieldset className="availability"><legend>参加可能な実行担当</legend>{people.filter(p=>p.id!=='maesaki').map(p=><label key={p.id}><input type="checkbox" checked={!brief.excluded.includes(p.id)} onChange={e=>setBrief({...brief,excluded:e.target.checked?brief.excluded.filter(id=>id!==p.id):[...brief.excluded,p.id]})}/>{p.name}</label>)}<p>前﨑店長を最終判断者として配置。実際の稼働余力は開始前に確認してください。</p></fieldset></details>
 <div className="form-footer"><small>不明な情報は「未確認」のまま初稿を作成できます。</small><button className="primary" type="submit">編成と指示の初稿を作る<ArrowRight size={18}/></button></div></form></section>
 <aside className="home-side"><section className="dark-panel"><small>MISSION PROTOCOL</small><h2>課題を、<br/>チームの行動へ。</h2><ol><li><span>01</span><div><b>課題を整理</b><p>目的・制約・不足情報を分ける</p></div></li><li><span>02</span><div><b>組織を編成</b><p>登録能力と専門性で担当を決める</p></div></li><li><span>03</span><div><b>指示を具体化</b><p>行動・期限・報告・裁量まで</p></div></li></ol><p className="side-note">MBTIは能力の判定に使わず、<br/>指示の伝え方を調整します。</p></section><section className="panel compact"><small>WORKSPACE STATUS</small><div className="metric"><b>{active.length}</b><span>実行中のミッション</span></div><div className="metric"><b>{store.missions.length}</b><span>保存済みミッション</span></div></section></aside></div>
 <section className="squad-section"><div className="section-title"><div><small>YOUR OPERATIVES</small><h2>このチームで、突破する。</h2></div><span>07 MEMBERS / 登録人材</span></div><div className="squad-roster">{people.map(p=><button className="operative-card" key={p.id} onClick={()=>{setMember(p.id);setBook(p.mbti);setView('members');window.scrollTo(0,0);}}><OperativePortrait memberId={p.id}/><div className="operative-info"><div className="operative-role"><RoleEmblem memberId={p.id}/><small>{p.role}</small></div><b>{p.name}</b><span>{p.mbti}</span><p>{p.specialty}</p></div></button>)}</div><p className="portrait-note">役割を表現したイメージイラストです。本人の容姿やMBTIによる能力評価を表すものではありません。</p></section><section className="resume-section"><div className="section-title"><h2>保存したミッション</h2><span>続きから再開</span></div>{store.missions.length===0?<div className="empty"><Flag size={24}/><p>最初のミッションを作成すると、ここからいつでも再開できます。</p></div>:<div className="mission-list">{store.missions.slice(0,5).map(m=><button className="mission-row" key={m.id} onClick={()=>select(m)}><span className={'status '+m.state}>{m.state==='active'?'実行中':'初稿'}</span><div><b>{m.brief.issue}</b><small>{kindLabels[m.kind]} · {m.commands.filter(c=>c.status==='done').length}/{m.commands.length} 完了</small></div><ArrowRight size={18}/></button>)}</div>}</section></>}
 {view==='control'&&!mission&&<div className="empty large"><Network size={36}/><h1>ミッションを始める</h1><p>課題を入力して、編成と具体的な指示を作成してください。</p><button className="primary" onClick={()=>setView('home')}>司令室へ</button></div>}
 {view==='control'&&mission&&<><div className="mission-heading"><div><small>{mission.state==='active'?'EXECUTION':'MISSION DRAFT'} / {kindLabels[mission.kind]}</small><h1>{mission.brief.issue}</h1><p>{mission.state==='active'?'承認した指示を実行中':'ルールによる初稿。入力と登録評価をもとにした提案です。'}</p></div><div className="heading-actions"><button className="secondary" onClick={()=>{setBrief({...mission.brief,excluded:[...mission.brief.excluded]});setView('home');}}>条件を変更して別案</button>{mission.state==='draft'&&<button className="primary" onClick={activate}>確認して実行を開始<ArrowRight size={16}/></button>}</div></div>
 <div className="mission-switch"><label>保存ミッション<select value={mission.id} onChange={e=>select(store.missions.find(m=>m.id===e.target.value)!)}>{store.missions.map(m=><option key={m.id} value={m.id}>{m.brief.issue}</option>)}</select></label><span>v{mission.version} · {fmt(mission.brief.deadline)}</span></div>
 <div className="tabs" role="tablist" aria-label="ミッション表示"><button role="tab" aria-selected={tab==='overview'} onClick={()=>setTab('overview')}>状況・組織</button><button role="tab" aria-selected={tab==='commands'} onClick={()=>setTab('commands')}>個別指示 <span>{mission.commands.length}</span></button></div>
 {tab==='overview'&&<><div className="dashboard-grid"><section className="panel current-goal"><small>CURRENT OBJECTIVE</small><h2>{mission.brief.goal||'達成したい状態を確認する'}</h2><p>{mission.brief.goal?'ユーザー入力':'未設定：実行開始前に目的を設定してください。'}</p><div className="progress-label"><span>タスク完了</span><b>{done} / {mission.commands.length}</b></div><progress value={done} max={mission.commands.length}/><div className="kpi-row"><div><small>KPI</small><b>{mission.brief.kpi||'未設定'}</b></div><div><small>現状 → 目標</small><b>{mission.brief.baseline||'未確認'} → {mission.brief.target||'未設定'}</b></div></div><small>出所：{mission.brief.source||'未確認'} ／ 期間：{mission.brief.period||'未設定'}</small></section><section className="panel next-action"><small>NEXT 30 MIN / 提案</small><h2>{nextTask?specs[nextTask.fn].name:'全タスクを確認済み'}</h2><p>{nextTask?.actions[0]||'結果検証を最終判断者へ提出してください。'}</p><div className="owner-chip"><Users size={16}/>{nextTask?nameOf(nextTask.owner):'前﨑店長'}</div><hr/><small>NEXT CHECKPOINT</small><b className="checkpoint">{fmt(mission.brief.checkpoint)}</b><button className="text-button" onClick={()=>setTab('commands')}>指示を確認する<ArrowRight size={16}/></button></section></div>
 <div className="two-column"><section className="panel"><div className="section-label"><Target size={18}/>ミッション分析<span>仮説と事実</span></div><dl className="analysis-list"><dt>一次分析・仮説</dt><dd>{mission.analysis.hypothesis}</dd><dt>成功条件</dt><dd>{mission.analysis.success}</dd><dt>制約（ユーザー入力）</dt><dd>{mission.brief.constraints||'未確認。予算・人員・営業条件を開始前に確認。'}</dd></dl><div className="unknowns"><b>開始前に確認すること</b><ul>{mission.analysis.unknowns.map(x=><li key={x}>{x}</li>)}</ul></div></section><section className="panel"><div className="section-label"><ShieldAlert size={18}/>リスクと要判断事項</div><ol className="risk-list">{mission.analysis.risks.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol><p className="subtle">予算・人員・営業方針の変更は店長へ相談。安全問題・重大クレームは即時報告。</p>{mission.commands.filter(c=>c.status==='blocked').map(c=><div className="blocker" key={c.id}><b>{nameOf(c.owner)}：{specs[c.fn].name}</b><p>{c.evidence||'相談内容を指示の確認記録へ記載してください。'}</p><small>報告先：{nameOf(c.reportTo)}</small></div>)}</section></div>
 <section className="panel organization"><div className="section-label"><Network size={18}/>指揮系統<span>工程順とは独立</span></div><div className="org-tree">{(['COMMANDER','LEADER','MEMBER'] as const).map(role=><div className={'org-tier '+role.toLowerCase()} key={role}><span>{role}</span><div>{mission.team.filter(t=>t.role===role).map(t=><article key={t.memberId}><OperativePortrait memberId={t.memberId}/><RoleEmblem memberId={t.memberId}/><small>{people.find(p=>p.id===t.memberId)?.mbti}</small><b>{nameOf(t.memberId)}</b><p>{t.role==='COMMANDER'?'最終判断・資源配分':t.functions.map(f=>specs[f].name).join('・')}</p><em>{t.reportsTo?'報告 → '+nameOf(t.reportsTo):'最終判断者'}</em></article>)}</div></div>)}</div><div className="process-strip"><small>成果物の引継ぎ順</small><p>{mission.commands.map(c=>specs[c.fn].name).join(' → ')}</p><span>成果物の引継ぎ相手と、直属の報告先は別です。</span></div></section>
 <section className="panel"><div className="section-label"><Clipboard size={18}/>状況メモ<span>実行記録</span></div><label className="field">発生した事実・相談事項<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="変化した状況、判断が必要なことを記録"/></label><button className="secondary" onClick={()=>updateMission({...mission,notes})}>状況メモを保存</button></section></>}
 {tab==='commands'&&<><div className="command-intro"><div><h2>誰が、何を、いつまでに。</h2><p>報告先・完了条件・裁量を含む、実行用の指示です。</p></div><button className="secondary" onClick={()=>download('mission-commands.json',JSON.stringify(mission,null,2))}><Download size={16}/>このミッションを書出す</button></div><div className="command-list">{mission.commands.map((c,i)=><article className="panel command-card" key={c.id}><div className="command-top"><div className="command-portrait"><OperativePortrait memberId={c.owner}/><span className="step">{String(i+1).padStart(2,'0')}</span></div><div><small>{specs[c.fn].name}</small><h3>{nameOf(c.owner)}</h3></div><span className={'task-state '+c.status}>{stateNames[c.status]}</span></div><div className="command-authority"><span>指示：{nameOf(c.issuer)} → {nameOf(c.owner)}</span><span>報告先：{nameOf(c.reportTo)}</span></div><h4>{c.purpose}</h4><ol className="action-list">{c.actions.map((x,i)=><li key={i}>{x}</li>)}</ol><div className="command-facts"><div><small>期限 / 日本時間</small><b className={!c.due?'missing':''}>{fmt(c.due)}</b></div><div><small>成果物</small><b>{c.output}</b></div></div><div className="completion"><Check size={17}/><div><small>完了条件</small><p>{c.done}</p></div></div><details><summary>報告・裁量・選定理由を確認<ChevronDown size={16}/></summary><dl className="analysis-list"><dt>報告タイミング</dt><dd>{c.reportWhen}</dd><dt>自分で判断してよい範囲</dt><dd>{c.discretion}</dd><dt>相談すべき条件</dt><dd>{c.consult}</dd><dt>即時報告</dt><dd>{c.immediate}</dd><dt>担当理由</dt><dd>{c.reason}</dd><dt>代替候補</dt><dd>{c.alternative}</dd><dt>伝え方の調整</dt><dd>{c.style}</dd><dt>先行成果物</dt><dd>{c.dependsOn.map(id=>specs[mission.commands.find(x=>x.id===id)!.fn].name).join('・')||'なし。最初に着手する。'}</dd><dt>優先度</dt><dd>{c.priority}</dd></dl></details>{c.evidence&&<div className="evidence"><small>成果物・確認結果</small><p>{c.evidence}</p></div>}<div className="card-actions"><button className="secondary" onClick={()=>copy(c)}><Clipboard size={16}/>指示をコピー</button><button className="primary" onClick={()=>{setEditor({...c,actions:[...c.actions]});setError('');}}>指示・状態を編集</button></div></article>)}</div></>}
 </>}
 {view==='members'&&<><div className="page-heading"><div><small>PEOPLE & WORK</small><h1>能力を主軸に、伝え方を調整。</h1><p>登録済みの評価です。実績・評価者・更新日は未確認。MBTIから能力を推定しません。</p></div></div><div className="member-grid">{people.map(p=><button key={p.id} className={'member-card '+(member===p.id?'selected':'')} onClick={()=>{setMember(p.id);setBook(p.mbti);}}><OperativePortrait memberId={p.id}/><RoleEmblem memberId={p.id}/><div><b>{p.name}</b><small>{p.mbti} · {p.specialty}</small></div></button>)}</div><section className="panel"><div className="section-label"><Users size={18}/>{currentMember.name}の登録能力<span>端末内の設定</span></div><p className="subtle">強い＝主担当候補、標準＝補助可能、支援前提＝支援が必要、未評価＝判断保留。変更は次の編成に反映し、既存の指示は変更しません。</p><div className="capability-grid">{abilityNames.map((label,i)=><label key={label}>{label}<select aria-label={currentMember.name+' '+label} value={assessment(currentMember,i+1,store.overrides)} onChange={e=>persist({...store,overrides:{...store.overrides,[currentMember.id+':'+(i+1)]:e.target.value as Level}})}><option value="strong">強い</option><option value="standard">標準</option><option value="growth">支援前提</option><option value="unknown">未評価</option></select></label>)}</div></section><section className="panel"><div className="section-label"><Compass size={18}/>16タイプの協働参考</div><p className="subtle">仕事上の仮説として利用します。本人の希望と実際の反応を優先してください。</p><div className="type-selector">{typeBook.map(t=><button key={t.mbti} className={book===t.mbti?'selected':''} onClick={()=>setBook(t.mbti)}>{t.mbti}</button>)}</div>{typeBook.filter(t=>t.mbti===book).map(t=><div className="type-reference" key={t.mbti}><h2>{t.mbti} / {t.jp}</h2><p>{t.work}</p><dl className="analysis-list"><dt>伝え方の参考</dt><dd>{t.request}</dd><dt>観察して調整する点</dt><dd>{t.watch}</dd><dt>認知機能（参考モデル）</dt><dd>{functionStack[t.mbti]}</dd></dl></div>)}</section></>}
 {view==='records'&&<><div className="page-heading"><div><small>CONTINUITY</small><h1>仕事の続きを、失わない。</h1><p>この端末のブラウザーに保存します。バックアップは書出して保管してください。</p></div></div><section className="panel"><div className="section-label"><Download size={18}/>バックアップと復元</div><div className="backup-actions"><button className="primary" onClick={exportAll}><Download size={17}/>全データを書き出す</button><label className="upload-button"><Upload size={17}/>バックアップを追加<input type="file" accept=".json,application/json" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label><button className="secondary" onClick={rawExport}>旧データ・原データを書出す</button></div><p className="subtle">全データのバックアップを読込みます。同じIDは上書きせず拒否します。能力設定はこの端末の既存設定を優先します。</p></section><section><div className="section-title"><h2>保存したミッション</h2><span>{store.missions.length}件</span></div><div className="mission-list">{store.missions.map(m=><button className="mission-row" key={m.id} onClick={()=>select(m)}><span className={'status '+m.state}>{m.state==='active'?'実行中':'初稿'}</span><div><b>{m.brief.issue}</b><small>{new Date(m.updatedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})} · v{m.version}</small></div><ArrowRight size={18}/></button>)}</div></section><section className="panel legacy"><h2>旧バージョンの履歴</h2><p>旧保存キーは変更せず、原文を保護しています。</p>{store.legacy.history?<details><summary>旧履歴の原文を表示</summary><pre>{store.legacy.history}</pre></details>:<p className="subtle">この端末で旧履歴は見つかっていません。</p>}</section></>}
 <footer>TEAM ARCHITECT 2.0 · B1 <span>組織設計を、次の行動へ。</span></footer></main></div>
 {editor&&mission&&<div className="modal-backdrop"><section ref={dialogRef} className="editor panel" role="dialog" aria-modal="true" aria-label="個別指示を編集"><div className="section-title"><h2>{nameOf(editor.owner)} / {specs[editor.fn].name}</h2><button className="secondary" onClick={()=>setEditor(null)}>閉じる</button></div><form onSubmit={saveCommand}><div className="field-grid"><label className="field">状態<select aria-label="状態" value={editor.status} onChange={e=>setEditor({...editor,status:e.target.value as Status})}>{Object.entries(stateNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field">期限（日本時間）<input type="datetime-local" value={editor.due} onChange={e=>setEditor({...editor,due:e.target.value})}/></label></div><label className="field">目的<input required value={editor.purpose} onChange={e=>setEditor({...editor,purpose:e.target.value})}/></label><label className="field">具体的行動（1行につき1項目）<textarea required rows={4} value={editor.actions.join('\n')} onChange={e=>setEditor({...editor,actions:e.target.value.split('\n')})}/></label>{([['done','完了条件'],['output','成果物'],['reportWhen','報告タイミング'],['discretion','自分で判断してよい範囲'],['consult','相談すべき条件'],['immediate','即時報告条件']] as const).map(([k,l])=><label className="field" key={k}>{l}<textarea required rows={2} value={editor[k]} onChange={e=>setEditor({...editor,[k]:e.target.value})}/></label>)}<label className="field">成果物・確認結果・相談内容<textarea value={editor.evidence} onChange={e=>setEditor({...editor,evidence:e.target.value})} placeholder="完了時は成果物の場所と確認結果を記載"/></label>{error&&<p className="editor-error" role="alert">{error}</p>}<div className="editor-footer"><button className="secondary" type="button" onClick={()=>setEditor(null)}>キャンセル</button><button className="primary" type="submit">変更を保存<Check size={16}/></button></div></form></section></div>}
 {view!=='home'&&<button className="mobile-new" aria-label="新しいミッション" onClick={()=>{setBrief({...blankBrief});setView('home');window.scrollTo(0,0);}}><Plus size={20}/></button>}
 </div>;
}

